// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: cmd/proto/logger.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
// const _ = grpc.SupportPackageIsVersion9
const _ = grpc.SupportPackageIsVersion8

const (
	MetricsBunch_AddBunch_FullMethodName = "/logger.MetricsBunch/AddBunch"
)

// MetricsBunchClient is the client API for MetricsBunch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsBunchClient interface {
	AddBunch(ctx context.Context, in *AddBunchRequest, opts ...grpc.CallOption) (*AddBunchResponse, error)
}

type metricsBunchClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsBunchClient(cc grpc.ClientConnInterface) MetricsBunchClient {
	return &metricsBunchClient{cc}
}

func (c *metricsBunchClient) AddBunch(ctx context.Context, in *AddBunchRequest, opts ...grpc.CallOption) (*AddBunchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBunchResponse)
	err := c.cc.Invoke(ctx, MetricsBunch_AddBunch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsBunchServer is the server API for MetricsBunch service.
// All implementations must embed UnimplementedMetricsBunchServer
// for forward compatibility.
type MetricsBunchServer interface {
	AddBunch(context.Context, *AddBunchRequest) (*AddBunchResponse, error)
	mustEmbedUnimplementedMetricsBunchServer()
}

// UnimplementedMetricsBunchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsBunchServer struct{}

func (UnimplementedMetricsBunchServer) AddBunch(context.Context, *AddBunchRequest) (*AddBunchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBunch not implemented")
}
func (UnimplementedMetricsBunchServer) mustEmbedUnimplementedMetricsBunchServer() {}
func (UnimplementedMetricsBunchServer) testEmbeddedByValue()                      {}

// UnsafeMetricsBunchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsBunchServer will
// result in compilation errors.
type UnsafeMetricsBunchServer interface {
	mustEmbedUnimplementedMetricsBunchServer()
}

func RegisterMetricsBunchServer(s grpc.ServiceRegistrar, srv MetricsBunchServer) {
	// If the following call pancis, it indicates UnimplementedMetricsBunchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricsBunch_ServiceDesc, srv)
}

func _MetricsBunch_AddBunch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBunchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsBunchServer).AddBunch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsBunch_AddBunch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsBunchServer).AddBunch(ctx, req.(*AddBunchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricsBunch_ServiceDesc is the grpc.ServiceDesc for MetricsBunch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsBunch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logger.MetricsBunch",
	HandlerType: (*MetricsBunchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBunch",
			Handler:    _MetricsBunch_AddBunch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/proto/logger.proto",
}
