// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: cmd/proto/logger.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Delta         int64                  `protobuf:"fixed64,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_cmd_proto_logger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_logger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_cmd_proto_logger_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metric) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Metric) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Bunch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        []*Metric              `protobuf:"bytes,1,rep,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bunch) Reset() {
	*x = Bunch{}
	mi := &file_cmd_proto_logger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bunch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bunch) ProtoMessage() {}

func (x *Bunch) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_logger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bunch.ProtoReflect.Descriptor instead.
func (*Bunch) Descriptor() ([]byte, []int) {
	return file_cmd_proto_logger_proto_rawDescGZIP(), []int{1}
}

func (x *Bunch) GetMetric() []*Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type AddBunchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bunch         *Bunch                 `protobuf:"bytes,1,opt,name=bunch,proto3" json:"bunch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBunchRequest) Reset() {
	*x = AddBunchRequest{}
	mi := &file_cmd_proto_logger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBunchRequest) ProtoMessage() {}

func (x *AddBunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_logger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBunchRequest.ProtoReflect.Descriptor instead.
func (*AddBunchRequest) Descriptor() ([]byte, []int) {
	return file_cmd_proto_logger_proto_rawDescGZIP(), []int{2}
}

func (x *AddBunchRequest) GetBunch() *Bunch {
	if x != nil {
		return x.Bunch
	}
	return nil
}

type AddBunchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBunchResponse) Reset() {
	*x = AddBunchResponse{}
	mi := &file_cmd_proto_logger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBunchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBunchResponse) ProtoMessage() {}

func (x *AddBunchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_logger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBunchResponse.ProtoReflect.Descriptor instead.
func (*AddBunchResponse) Descriptor() ([]byte, []int) {
	return file_cmd_proto_logger_proto_rawDescGZIP(), []int{3}
}

func (x *AddBunchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_cmd_proto_logger_proto protoreflect.FileDescriptor

var file_cmd_proto_logger_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x67,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72,
	0x22, 0x58, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x10, 0x52, 0x05, 0x64,
	0x65, 0x6c, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2f, 0x0a, 0x05, 0x42, 0x75,
	0x6e, 0x63, 0x68, 0x12, 0x26, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x22, 0x36, 0x0a, 0x0f, 0x41,
	0x64, 0x64, 0x42, 0x75, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23,
	0x0a, 0x05, 0x62, 0x75, 0x6e, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x42, 0x75, 0x6e, 0x63, 0x68, 0x52, 0x05, 0x62, 0x75,
	0x6e, 0x63, 0x68, 0x22, 0x28, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x42, 0x75, 0x6e, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x4d, 0x0a,
	0x0c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x42, 0x75, 0x6e, 0x63, 0x68, 0x12, 0x3d, 0x0a,
	0x08, 0x41, 0x64, 0x64, 0x42, 0x75, 0x6e, 0x63, 0x68, 0x12, 0x17, 0x2e, 0x6c, 0x6f, 0x67, 0x67,
	0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x42, 0x75, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x42,
	0x75, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c,
	0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_cmd_proto_logger_proto_rawDescOnce sync.Once
	file_cmd_proto_logger_proto_rawDescData []byte
)

func file_cmd_proto_logger_proto_rawDescGZIP() []byte {
	file_cmd_proto_logger_proto_rawDescOnce.Do(func() {
		file_cmd_proto_logger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_proto_logger_proto_rawDesc), len(file_cmd_proto_logger_proto_rawDesc)))
	})
	return file_cmd_proto_logger_proto_rawDescData
}

var file_cmd_proto_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cmd_proto_logger_proto_goTypes = []any{
	(*Metric)(nil),           // 0: logger.Metric
	(*Bunch)(nil),            // 1: logger.Bunch
	(*AddBunchRequest)(nil),  // 2: logger.AddBunchRequest
	(*AddBunchResponse)(nil), // 3: logger.AddBunchResponse
}
var file_cmd_proto_logger_proto_depIdxs = []int32{
	0, // 0: logger.Bunch.metric:type_name -> logger.Metric
	1, // 1: logger.AddBunchRequest.bunch:type_name -> logger.Bunch
	2, // 2: logger.MetricsBunch.AddBunch:input_type -> logger.AddBunchRequest
	3, // 3: logger.MetricsBunch.AddBunch:output_type -> logger.AddBunchResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cmd_proto_logger_proto_init() }
func file_cmd_proto_logger_proto_init() {
	if File_cmd_proto_logger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_proto_logger_proto_rawDesc), len(file_cmd_proto_logger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_proto_logger_proto_goTypes,
		DependencyIndexes: file_cmd_proto_logger_proto_depIdxs,
		MessageInfos:      file_cmd_proto_logger_proto_msgTypes,
	}.Build()
	File_cmd_proto_logger_proto = out.File
	file_cmd_proto_logger_proto_goTypes = nil
	file_cmd_proto_logger_proto_depIdxs = nil
}
